# Generated by Django 2.2.5 on 2020-01-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('locationName', models.CharField(max_length=30)),
                ('latitude', models.FloatField(default=-2000, max_length=30)),
                ('longtitude', models.FloatField(default=-2000, max_length=30)),
            ],
        ),
    ]
